from .OPTPhaseAssessment import OPTPhaseAssessment
from .EnduranceAssessment import EnduranceAssessment
from .FlexibilityAssessment import FlexibilityAssessment
from .PowerAssessment import PowerAssessment
from .StabilizationAssessment import StabilizationAssessment
from .StrengthAssessment import StrengthAssessment
